version: '3.8'

services:
    app:
        build: .
        container_name: url-shortener-app
        restart: unless-stopped
        working_dir: /var/www
        environment:
            - DB_HOST=db
            - DB_DATABASE=shortener
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost:8000
        ports:
            - "9000:9000"
        depends_on:
            - db
        volumes:
            - ./storage:/var/www/storage
            - ./bootstrap/cache:/var/www/bootstrap/cache
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: url-shortener-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: url-shortener-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: shortener
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
