version: '3.8'

services:
  app:
    build: .
    image: url-shortener-app
    container_name: url-shortener-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./bootstrap:/var/www/bootstrap
      - ./public:/var/www/public
      - ./artisan:/var/www/artisan
    environment:
      - DB_HOST=db
      - DB_DATABASE=shortener
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - APP_ENV=local
      - APP_DEBUG=true
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: url-shortener-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: url-shortener-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shortener
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: 