services:
    app:
        build: .
        container_name: url-shortener-app
        restart: unless-stopped
        working_dir: /var/www
        environment:
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/identifier.sqlite
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost:8000
        ports:
            - "9000:9000"
        volumes:
            - ./storage:/var/www/storage
            - ./bootstrap/cache:/var/www/bootstrap/cache
            - ./database:/var/www/database
            - ./public:/var/www/public
            - ./resources:/var/www/resources
            - node_modules:/var/www/node_modules
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: url-shortener-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/public
            - ./public:/var/www/public
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    node_modules:
